### ISSUE TITLE
I've tried this chrome portable device emulator

### ISSUE THREAD

**Issue by joethuoo** [jonathanbharding/Bootstrap-3.1.1-OffCanvasMenu#1]
The problem comes when i try to emulate with different devices in the chrome emulator, the canvas doesn't respond.

**Comment by jonathanbharding** [comment]
What version of chrome are you using? I'm looking at it on chrome canary and it works great. Chrome Canary is their bleeding edge version. http://www.google.com/intl/en/chrome/browser/canary.html. I couldn't get it to work on older versions of Chrome, but I tried other sites and it didn't work either.

**Comment by joethuoo** [comment]
I guess it's the browser, chrome 37.0.2062.124m
